module.exports = {
  "meta_title": "HashDish - 写真で探せるあなたの近くの最高のレストラン",
  "meta_description": "HashDishはあなたの近くのベストなレストランで撮られている写真を表示します。もう食べる場所を探すのに困りません。",
  "meta_keywords": "HashDish, Japan, Tokyo, ramen, restaurants, travel, sushi, japanese, jiro, shibuya, Shinjuku, Roppongi, ginza",

  "meta_title_login": "Hashdish - ログイン",
  "meta_title_map": "Hashdish - マップ",
  "meta_title_search": "Hashdish - 検索",
  "meta_title_mypage": "Hashdish - マイページ",
  "meta_title_about": "Hashdish - HashDishとは",
  "meta_title_instagramer": "${0}さんが訪問したレストラン - Hashdish",
  "meta_title_detail": "Hashdish - ${0} / ${1}",

  "common_edit": "編集",
  "common_save": "保存",
  "common_cancel": "キャンセル",
  "common_close": "閉じる",
  "common_done": "決定",
  "common_now_open": "開店中",
  "common_google_map": "Google Map",
  "common_powered_by": "Powered By",
  "common_prev": "前",
  "common_next": "次",
  "common_email": "Email",
  "common_today": "本日",
  "common_readmore": "もっと読む",
  "common_hide": "隠す",
  "common_list": "リスト",
  "common_map": "マップ",

  "nav_explore": "写真で探す",
  "nav_about": "HashDishとは",
  "nav_settings": "設定",
  "nav_login": "ログイン",
  "nav_logout": "ログアウト",
  "nav_mypage": "マイページ",

  "about_title": "HashDish",
  "about_desc1": "写真で探せるあなたの近くの最高のレストラン。",
  "about_desc2": "HashDishはあなたの近くのベストなレストランで撮られている写真を表示します。もう食べる場所を探すのに困りません。",

  "sns_fb": "Facebook",
  "sns_tw": "Twitter",
  "sns_line": "LINE",

  "header_search_placeholder": "検索",

  "top_no_results": "結果なし",

  "search_no_results": "検索結果なし",

  "preview_link_restaurant": "このホテルを見る",

  "mypage_summary": "<strong>${0}</strong>件のお気に入り写真 (レストラン <strong>${1}</strong>件)",
  "mypage_no_liked_photos": "まだイイねをしていません。",

  "detail_table_title_phone": "電話番号",
  "detail_table_title_budget": "予算",
  "detail_table_title_open_hours": "営業時間",
  "detail_table_title_shop_holidays": "定休日",
  "detail_table_title_cards": "カード",
  "detail_table_title_smoking_availability": "禁煙・喫煙",
  "detail_table_title_number_of_seats": "席数",
  "detail_table_title_tags": "ハッシュタグ",
  "detail_title_popular_photos": "人気の写真",

  "login_title": "写真で探せるあなたの近くの最高のレストラン。",
  "login_note": "HashDishがあなたの許可なしにSNSへ投稿することはありません。",
  "login_fb_btn": "Facebookでログイン",
  "login_tw_btn": "Twitterでログイン",

  "queries_area": "エリア",
  "queries_area_all": "全てのエリア",
  "queries_sort": "ソート",
  "queries_sort_by_like_count": "人気順",
  "queries_sort_by_distance": "距離が近い順",
  "queries_sort_by_rating": "レストランの評価が高い順",
  "queries_budget_range": "予算範囲",
  "queries_budget_range_lunch": "ランチ",
  "queries_budget_range_dinner": "ディナー",

  "filter_sort_by": "${0}でソート",

  "open_hours_lo": "L.O.",
  "open_hours_closed": "休み",

  "availability_yes": "Yes",
  "availability_no": "No",
  "availability_smoking_sectionalized": "分煙",

  "card_visa": "Visa",
  "card_master": "Master",
  "card_jcb": "JCB",
  "card_amex": "Amex",
  
  "error_general": "エラーが発生しました。",
  "error_auth": "認証に失敗しました。",

  "warning_location_service_off": "ブラウザの位置情報サービスが許可されていません。近い距離でソートするためには位置情報サービスを使用するようにしてください。",

  "constants_DayOfWeek_sunday": "日曜",
  "constants_DayOfWeek_monday": "月曜",
  "constants_DayOfWeek_tuesday": "火曜",
  "constants_DayOfWeek_wednesday": "水曜",
  "constants_DayOfWeek_thursday": "木曜",
  "constants_DayOfWeek_friday": "金曜",
  "constants_DayOfWeek_saturday": "土曜",
  "constants_holidays_holiday": "祝日",
  "constants_holidays_irregular": "不定休",

  "constants_sort_-like_count": "人気順",
  "constants_sort_-rating": "レストランの評価順",
  "constants_sort_$near": "距離順",

  "constants_budget_type_lunch": "ランチ",
  "constants_budget_type_dinner": "ディナー",

  "constants_area_JP_tokyo_A1301": "銀座・新橋・有楽町",
  "constants_area_JP_tokyo_A1307": "六本木・麻布・広尾",
  "constants_area_JP_tokyo_A1303": "渋谷・恵比寿・代官山",
  "constants_area_JP_tokyo_A1306": "原宿・表参道・青山",
  "constants_area_JP_tokyo_A1311": "上野・浅草・日暮里",
  "constants_area_JP_tokyo_A1302": "東京・日本橋",
  "constants_area_JP_tokyo_A1310": "秋葉原・神田・水道橋",
  "constants_area_JP_tokyo_A1304": "新宿・代々木・大久保",
  "constants_area_JP_tokyo_A1313": "築地・湾岸・お台場",

  // resources only for server side
  "constants_area_JP_aichi": "愛知",
  "constants_area_JP_akita": "秋田",
  "constants_area_JP_aomori": "青森",
  "constants_area_JP_chiba": "千葉",
  "constants_area_JP_ehime": "愛媛",
  "constants_area_JP_fukui": "福井",
  "constants_area_JP_fukuoka": "福岡",
  "constants_area_JP_fukushima": "福島",
  "constants_area_JP_gifu": "岐阜",
  "constants_area_JP_gunma": "群馬",
  "constants_area_JP_hiroshima": "広島",
  "constants_area_JP_hokkaido": "北海道",
  "constants_area_JP_hyogo": "兵庫",
  "constants_area_JP_ibaraki": "茨城",
  "constants_area_JP_ishikawa": "石川",
  "constants_area_JP_iwate": "岩手",
  "constants_area_JP_kagawa": "香川",
  "constants_area_JP_kagoshima": "鹿児島",
  "constants_area_JP_kanagawa": "神奈川",
  "constants_area_JP_kochi": "高知",
  "constants_area_JP_kumamoto": "熊本",
  "constants_area_JP_kyoto": "京都",
  "constants_area_JP_mie": "三重",
  "constants_area_JP_miyagi": "宮城",
  "constants_area_JP_miyazaki": "宮崎",
  "constants_area_JP_nagano": "長野",
  "constants_area_JP_nagasaki": "長崎",
  "constants_area_JP_nara": "奈良",
  "constants_area_JP_niigata": "新潟",
  "constants_area_JP_oita": "大分",
  "constants_area_JP_okayama": "岡山",
  "constants_area_JP_okinawa": "沖縄",
  "constants_area_JP_osaka": "大阪",
  "constants_area_JP_saga": "佐賀",
  "constants_area_JP_saitama": "埼玉",
  "constants_area_JP_shiga": "滋賀",
  "constants_area_JP_shimane": "島根",
  "constants_area_JP_shizuoka": "静岡",
  "constants_area_JP_tochigi": "栃木",
  "constants_area_JP_tokushima": "徳島",
  "constants_area_JP_tokyo": "東京",
  "constants_area_JP_tottori": "鳥取",
  "constants_area_JP_toyama": "富山",
  "constants_area_JP_wakayama": "和歌山",
  "constants_area_JP_yamagata": "山形",
  "constants_area_JP_yamaguchi": "山口",
  "constants_area_JP_yamanashi": "山梨",

  "_dummy": null
}