module.exports = {
  "meta_title": "HashDish - The most visual way to find the best restaurants",
  "meta_description": "HashDish lets you browse through pictures of the best nearby restaurants uploaded by real customers. Never waste your time searching for places to eat near you.",
  "meta_keywords": "HashDish, Japan, Tokyo, ramen, restaurants, travel, sushi, japanese, jiro, shibuya, Shinjuku, Roppongi, ginza",

  "meta_title_login": "Hashdish - Login",
  "meta_title_map": "Hashdish - Map",
  "meta_title_search": "Hashdish - Search",
  "meta_title_mypage": "Hashdish - My Page",
  "meta_title_about": "Hashdish - About",
  "meta_title_instagramer": "${0} visited restaurants - Hashdish",
  "meta_title_detail": "${0} / ${1} - Hashdish",

  "common_edit": "Edit",
  "common_save": "Save",
  "common_cancel": "Cancel",
  "common_close": "Close",
  "common_done": "Done",
  "common_now_open": "Now Open",
  "common_google_map": "Google Map",
  "common_powered_by": "Powered By",
  "common_prev": "Prev",
  "common_next": "Next",
  "common_email": "Email",
  "common_today": "Today",
  "common_readmore": "Read More",
  "common_hide": "Hide",
  "common_list": "list",
  "common_map": "map",

  "nav_explore": "Explore",
  "nav_about": "About",
  "nav_settings": "Settings",
  "nav_login": "Login",
  "nav_logout": "Logout",
  "nav_mypage": "My Page",

  "about_title": "HashDish",
  "about_desc1": "The most visual way to find the best restaurants.",
  "about_desc2": "HashDish lets you browse through pictures of the best nearby restaurants uploaded by real customers. Never waste your time searching for places to eat near you.",

  "sns_fb": "Facebook",
  "sns_tw": "Twitter",
  "sns_line": "LINE",

  "header_search_placeholder": "Search",

  "top_no_results": "No results",

  "search_no_results": "No search results",

  "preview_link_restaurant": "See This Hotel",

  "mypage_summary": "<strong>${0}</strong> saved dishes in <strong>${1}</strong> restaurants.",
  "mypage_no_liked_photos": "You have not liked photos yet.",

  "detail_table_title_phone": "Tel",
  "detail_table_title_budget": "Budget",
  "detail_table_title_open_hours": "Open Hours",
  "detail_table_title_shop_holidays": "Closed on",
  "detail_table_title_cards": "Credit Card",
  "detail_table_title_smoking_availability": "Smoking",
  "detail_table_title_number_of_seats": "Number of Seats",
  "detail_table_title_tags": "Hashtags",
  "detail_title_popular_photos": "Popular Photos",

  "login_title": "Find The Best Dish in Tokyo Through Pictures",
  "login_note": "We won't post anything without your permission.",
  "login_fb_btn": "Login with Facebook",
  "login_tw_btn": "Login with Twitter",

  "queries_area": "Area",
  "queries_area_all": "All Area",
  "queries_sort": "Sort",
  "queries_sort_by_like_count": "Sort by popular",
  "queries_sort_by_distance": "Sort by distance",
  "queries_sort_by_rating": "Sort by restaurant rating",
  "queries_budget_range": "Budget Range",
  "queries_budget_range_lunch": "Lunch",
  "queries_budget_range_dinner": "Dinner",

  "filter_sort_by": "Sort by ${0}",

  "open_hours_lo": "L.O.",
  "open_hours_closed": "Closed",

  "availability_yes": "Yes",
  "availability_no": "No",
  "availability_smoking_sectionalized": "Sectionalized",

  "card_visa": "Visa",
  "card_master": "Master",
  "card_jcb": "JCB",
  "card_amex": "Amex",
  
  "error_general": "An error occurs",
  "error_auth": "Authentication error",

  "warning_location_service_off": "Location service in the browser is not allowed for Hashdish. Please enable location service to sort by near distances.",

  "constants_DayOfWeek_sunday": "Sunday",
  "constants_DayOfWeek_monday": "Monday",
  "constants_DayOfWeek_tuesday": "Tuesday",
  "constants_DayOfWeek_wednesday": "Wednesday",
  "constants_DayOfWeek_thursday": "Thursday",
  "constants_DayOfWeek_friday": "Friday",
  "constants_DayOfWeek_saturday": "Saturday",
  "constants_holidays_holiday": "Holiday",
  "constants_holidays_irregular": "Irregular",

  "constants_sort_-like_count": "popular",
  "constants_sort_-rating": "restaurant rating",
  "constants_sort_$near": "distance",

  "constants_budget_type_lunch": "Lunch",
  "constants_budget_type_dinner": "Dinner",

  "constants_area_JP_tokyo_A1301": "Ginza・Shinbashi・Yurakucho",
  "constants_area_JP_tokyo_A1307": "Roppongi・Azabu・Hiroo",
  "constants_area_JP_tokyo_A1303": "Shibuya・Ebisu・Daikanyama",
  "constants_area_JP_tokyo_A1306": "Harajuku・Omotesando・Aoyama",
  "constants_area_JP_tokyo_A1311": "Ueno・Asakusa・Noppori",
  "constants_area_JP_tokyo_A1302": "Tokyo・Nihonbashi",
  "constants_area_JP_tokyo_A1310": "Akihabara・Kanda・Suidobashi",
  "constants_area_JP_tokyo_A1304": "Shinjuku・Yoyogi・Okubo",
  "constants_area_JP_tokyo_A1313": "Tsukiji・Odaiba",

  // resources only for server side
  "constants_area_JP_aichi": "Aichi",
  "constants_area_JP_akita": "Akita",
  "constants_area_JP_aomori": "Aomori",
  "constants_area_JP_chiba": "Chiba",
  "constants_area_JP_ehime": "Ehime",
  "constants_area_JP_fukui": "Fukui",
  "constants_area_JP_fukuoka": "Fukuoka",
  "constants_area_JP_fukushima": "Fukushima",
  "constants_area_JP_gifu": "Gifu",
  "constants_area_JP_gunma": "Gunma",
  "constants_area_JP_hiroshima": "Hiroshima",
  "constants_area_JP_hokkaido": "Hokkaido",
  "constants_area_JP_hyogo": "Hyogo",
  "constants_area_JP_ibaraki": "Ibaraki",
  "constants_area_JP_ishikawa": "Ishikawa",
  "constants_area_JP_iwate": "Iwate",
  "constants_area_JP_kagawa": "Kagawa",
  "constants_area_JP_kagoshima": "Kagoshima",
  "constants_area_JP_kanagawa": "Kanagawa",
  "constants_area_JP_kochi": "Kochi",
  "constants_area_JP_kumamoto": "Kumamoto",
  "constants_area_JP_kyoto": "Kyoto",
  "constants_area_JP_mie": "Mie",
  "constants_area_JP_miyagi": "Miyagi",
  "constants_area_JP_miyazaki": "Miyazaki",
  "constants_area_JP_nagano": "Nagano",
  "constants_area_JP_nagasaki": "Nagasaki",
  "constants_area_JP_nara": "Nara",
  "constants_area_JP_niigata": "Nigata",
  "constants_area_JP_oita": "Oita",
  "constants_area_JP_okayama": "Okayama",
  "constants_area_JP_okinawa": "Okinawa",
  "constants_area_JP_osaka": "Osaka",
  "constants_area_JP_saga": "Saga",
  "constants_area_JP_saitama": "Saitama",
  "constants_area_JP_shiga": "Shiga",
  "constants_area_JP_shimane": "Shimane",
  "constants_area_JP_shizuoka": "Shizuoka",
  "constants_area_JP_tochigi": "Tochigi",
  "constants_area_JP_tokushima": "Tokushima",
  "constants_area_JP_tokyo": "Tokyo",
  "constants_area_JP_tottori": "Tottori",
  "constants_area_JP_toyama": "Toyama",
  "constants_area_JP_wakayama": "Wakayama",
  "constants_area_JP_yamagata": "Yamagata",
  "constants_area_JP_yamaguchi": "Yamaguchi",
  "constants_area_JP_yamanashi": "Yamanashi",

  "_dummy": null
}